#!/bin/bash

echo "Executing link action=$SERVICE_ACTION type=$SERVICE_ACTION_TYPE"

ACTION_TO_EXECUTE="$SERVICE_ACTION_TYPE"

case "$SERVICE_ACTION_TYPE" in
  "custom")
    ACTION_TO_EXECUTE="$SERVICE_ACTION"
    ;;
  "create")
    ACTION_TO_EXECUTE="link"
    ;;
  "delete")
    ACTION_TO_EXECUTE="unlink"
    ;;
esac

INGRESS_TYPE="${INGRESS_TYPE:-alb}"

echo "INGRESS_TYPE is set to '$INGRESS_TYPE'"

WORKFLOW_PATH="$SERVICE_PATH/workflows/$INGRESS_TYPE/$ACTION_TO_EXECUTE.yaml"
OVERRIDES_WORKFLOW_PATH="$OVERRIDES_PATH/workflows/$INGRESS_TYPE/$ACTION_TO_EXECUTE.yaml"
VALUES_PATH="$SERVICE_PATH/values.yaml"

CMD="np service workflow exec --workflow $WORKFLOW_PATH --values $VALUES_PATH"

if [[ -f "$OVERRIDES_WORKFLOW_PATH" ]]; then
  CMD="$CMD --overrides $OVERRIDES_WORKFLOW_PATH"
fi

echo "Executing command: $CMD"
eval "$CMD"
